apiVersion: catalog.modeld.io/v1alpha1
kind: Algorithm
metadata:
  name: extra-tree-classifier
  namespace: modeld-catalog
  labels:
    app.kubernetes.io/part-of: modeld
spec:
  frameworkName: scikit-learn
  integerParameters:
    - name: min_samples_split
      minimum: 2
      maximum: 20
      defaultValue: 2
    - name : min_samples_leaf
      minimum: 1
      maximum: 20
      defaultValue: 1
