apiVersion: catalog.modeld.io/v1alpha1
kind: Algorithm
metadata:
  name: elasticnet
  namespace: modeld-catalog
  labels:
    app.kubernetes.io/part-of: modeld
spec:
  task: regression
  frameworkName: scikit-learn