apiVersion: catalog.modeld.io/v1alpha1
kind: Algorithm
metadata:
  name: adaboost
  namespace: modeld-catalog
  labels:
    app.kubernetes.io/part-of: modeld
spec:
  frameworkName: scikit-learn
  task: binary-classification
  integerParameters:
    - name: n_estimators
      type: number
      minimum: 50
      maximum: 500
      defaultValue: 50
  floatParameters:
    - name: learning_rate
      type: number
      minimum: 0.01
      maximum: 2
      defaultValue: 0.1
      log: true
  catagoricalParameters:
    - name: algorithm
      type: categorical
      enum:
        - SAMME.R
        - SAMME
      defaultValue: SAMME.R
