apiVersion: catalog.modeld.io/v1alpha1
kind: Algorithm
metadata:
  name: catboost
  namespace: modeld-catalog
  labels:
    app.kubernetes.io/part-of: modeld
spec:
  frameworkName: scikit-learn
  task: binary-classification