{{ if .Values.azure.create }}
apiVersion: infra.modeld.io/v1alpha1
kind: Credential
metadata:
  name: default-azure-credential
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
spec:
  provider: azure
  tenantRef:
    name: default-tenant
    namespace: modeld-system
  secretName : default-azure-secret
  {{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: default-azure-secret
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.azure.secret.storageAccessKey }}
  azure-storage-access-key: {{ .Values.azure.secret.storageAccessKey | b64enc | quote }}
  {{ else }}
  azure-storage-access-key: {{ required "azure access key is required!" .Values.azure.secret.storageAccessKey }}
  {{- end }}
  {{- if .Values.azure.storageAccountName }}
  azure-storage-account-name: {{ .Values.azure.secret.storageAccountName | b64enc | quote }}
  {{ else }}
  azure-storage-access-key: {{ required "azure access account is required!" .Values.azure.secret.storageAccountName }}
---
apiVersion: infra.modeld.io/v1alpha1
kind: VirtualBucket
metadata:
  name: default-azure-bucket
  namespace: default-tenant
spec:
  tenantRef:
    namespace: modeld-system
    name : default-tenant
  credentialName: default-azure-credential
{{ end }}
