{{ if .Values.gcp.create }}
apiVersion: infra.modeld.io/v1alpha1
kind: Credential
metadata:
  name: default-gcp-credentials
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
spec:
  provider: gcp
  tenantRef:
    name: default-tenant
    namespace: {{ .Release.Namespace }}
  secretName : default-gcp-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: default-gcp-secret
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
type: Opaque
stringData:
  gcp-az: {{ .Values.gcp.secret.az }}
  gcp-access-key: {{ .Values.gcp.secret.accessKey }}
  gcp-secret-key: {{ .Values.gcp.secret.secretKey }}
  gcp-keyfile: {{ .Values.gcp.secret.keyfile }}
  gcp-project: {{ .Values.gcp.secret.project }}
---
apiVersion: infra.modeld.io/v1alpha1
kind: VirtualBucket
metadata:
  name: default-gcp-bucket
  namespace: default-tenant
spec:
  tenantRef:
    namespace: modeld-system
    name : default-tenant
  credentialName: default-gcp-credential

{{ end }}