{{ if .Values.github.create }}
apiVersion: infra.modeld.io/v1alpha1
kind: Credential
metadata:
  name: {{ .Values.github.name }}
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
spec:
  provider: github
  tenantRef:
    name: default-tenant
    namespace: {{ .Release.Namespace }}
  secretName : default-github-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: default-github-secret
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.github.secret.token }}
  github-token : {{ .Values.github.secret.token | b64enc | quote }}
  {{ else }}
  github-token : {{ required "github token is required!" .Values.github.secret.token }}
  {{- end }}
  {{- if .Values.digitalocean.secret.token }}
  github-username : {{ .Values.github.secret.username | b64enc | quote }}
  {{ else }}
  github-username : {{ required "github username is required!" .Values.github.secret.username }}
  {{- end }}
{{ end }}


