apiVersion: catalog.modeld.io/v1alpha1
kind: Algorithm
metadata:
  name: knn-regressor
  namespace: modeld-catalog
  labels:
    app.kubernetes.io/part-of: modeld
spec:
  frameworkName: scikit-learn
  task: regression
  integerParameters:
    - name: n_neighbors
      minimum: 1
      maximum: 100
      log: true
      defaultValue: 1
  catagoricalParameters:
    - name: weights
      type: categorical
      enum:
          - uniform
          - distance
      defaultValue: uniform
    - name: p
      type: categorical
      enums:
          - 1
          - 2
      defaultValue: 2





