{{ if .Values.email.create }}
apiVersion: infra.modeld.io/v1alpha1
kind: Notifier
metadata:
  name: default-email-notifier
  namespace: default-tenant
spec:
  tenantRef:
    name: default-tenant
    namespace: modeld-system
  type: email
  email:
    to:
      - {{ .Values.email.to }}
    from: {{ .Values.email.from}}
    host: {{ .Values.email.host}}
    port: {{ .Values.email.port}}
    credentialName: {{ .Values.email.name }}
{{ end }}

