{{ if .Values.slack.create }}
apiVersion: infra.modeld.io/v1alpha1
kind: Notifier
metadata:
  name: default-slack-notifier
  namespace: default-tenant
spec:
  tenantRef:
    name: default-tenant
    namespace: modeld-system
  type: slack
  slack:
    webhook: {{ .Values.slack.webhook }}
{{ end }}
