{{ if .Values.dataproduct.create }}
apiVersion: data.modeld.io/v1alpha1
kind: DataProduct
metadata:
  namespace: default-tenant
  name: default-data-product
spec:
  gitRepoName: default-git-repository
  tenantRef:
    name: default-tenant
    namespace: modeld-system
  imageRepoName: iris
  bucketName: default-bucket
  servingSiteName: default-serving-site
  labName: default-lab
  task: binary-classification
  labelColumn: "class"
{{ end }}

