apiVersion: catalog.modeld.io/v1alpha1
kind: UserRoleClass
metadata:
  name: data-engineer
  namespace: modeld-catalog
spec:
  rules:
    - apiGroups: [""] # "" indicates the core API group
      resources: ["pods"]
      verbs: ["get", "watch", "list"]