apiVersion: catalog.modeld.io/v1alpha1
kind: TrainerClass
metadata:
  name: pytorch-trainer
  namespace: modeld-catalog
spec:
  image: gcr.io/modeld/trainer:latest
  tasks:
    - binary-classification
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modeld-trainer
    spec:
      containers:
        - name: main
          image: gcr.io/modeld/trainer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /home/modeld/data
        - name: sidecar
          image: gcr.io/modeld/clouds:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8090
          volumeMounts:
            - name: data
              mountPath: /home/modeld/data
      volumes:
        - name: data
          emptyDir: {}