{{ if .Values.dockerhub.create }}
apiVersion: v1
kind: Secret
metadata:
  name: default-dockerhub-secret
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.digitalocean.secret.token }}
  image-registry-host: {{ .Values.dockerhub.secret.registryHost | b64enc | quote }}
  {{ else }}
  image-registry-host: {{ required "image registry host is required!" .Values.dockerhub.secret.registryHost }}
  {{- end }}
  {{- if .Values.dockerhub.secret.username }}
  image-registry-username: {{ .Values.dockerhub.secret.username | b64enc | quote }}
  {{ else }}
  image-registry-username: {{ required "image registry username is required!" .Values.dockerhub.secret.username }}
  {{- end }}
  {{- if .Values.dockerhub.secret.password }}
  image-registry-password: {{ .Values.dockerhub.secret.password | b64enc | quote }}
  {{ else }}
  image-registry-password: {{ required "image registry secret is required!" .Values.dockerhub.secret.password }}
  {{- end }}

---
apiVersion: infra.modeld.io/v1alpha1
kind: Credential
metadata:
  name: default-dockerhub-credentials
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
spec:
  provider: docker-hub
  tenantRef:
    name: default-tenant
    namespace: {{ .Release.Namespace }}
  secretName : default-dockerhub-secret
{{ end }}