{{ if .Values.license.create }}
apiVersion: infra.modeld.io/v1alpha1
kind: Credential
metadata:
  name: default-license
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
spec:
  provider: license
  tenantRef:
    name: default-tenant
    namespace: modeld-system
  secretName : default-license-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: default-licnese-secret
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.license.secret.key }}
  key: {{ .Values.license.secret.key | b64enc | quote }}
  {{ else }}
  key : {{ required "license key is required!" .Values.license.secret.key }}
  {{- end }}
{{ end }}
