apiVersion: v1
kind: Service
metadata:
  name: modeld-controlplane-service
  namespace: modeld-system
  labels: {{- include "modeld.controlplane.labels" . | nindent 4 }}
spec:
  ports:
    - name: controlplane
      port: {{ .Values.controlplane.http.port }}
  selector: {{- include "modeld.controlplane.matchLabels" . | nindent 4 }}