apiVersion: v1
kind: Service
metadata:
  name: modeld-frontend-service
  namespace: modeld-system
  labels: {{- include "modeld.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: frontend
      port: {{ .Values.frontend.http.port }}
      targetPort: frontend
  selector: {{- include "modeld.frontend.matchLabels" . | nindent 4 }}