apiVersion: v1
kind: Service
metadata:
  name: modeld-publisher-service
  namespace: modeld-system
  labels: {{- include "modeld.publisher.labels" . | nindent 4 }}
spec:
  ports:
    - name: publisher
      port: {{ .Values.publisher.http.port }}
      targetPort: publisher
  selector: {{- include "modeld.publisher.matchLabels" . | nindent 4 }}