apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modeld-publisher-role-binding
  namespace: {{ .Release.Namespace }}
  labels: {{- include "modeld.publisher.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: modeld-publisher
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccount:modeld-system:modeld-publisher