{{ if .Values.minio.create }}
apiVersion: infra.modeld.io/v1alpha1
kind: Credential
metadata:
  name: default-minio
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
spec:
  provider: minio
  tenantRef:
    name: default-tenant
    namespace: {{ .Release.Namespace }}
  secretName : default-minio-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: default-minio-secret
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.minio.secret.accesskey }}
  minio-access-key : {{ .Values.minio.secret.accesskey | b64enc | quote }}
  {{ else }}
  minio-access-key : {{ required "minio access key is required!" .Values.minio.secret.accesskey }}
  {{- end }}

  {{- if .Values.minio.secret.secretkey }}
  minio-secret-key : {{ .Values.minio.secret.secretkey | b64enc | quote }}
  {{ else }}
  minio-secret-key : {{ required "minio secret key is required!" .Values.minio.secret.secretkey }}
  {{- end }}

  {{- if .Values.minio.secret.host }}
  minio-host : {{ .Values.minio.secret.host | b64enc | quote }}
  {{ else }}
  minio-host : {{ required "minio host is required!" .Values.minio.secret.host }}
  {{- end }}
---
apiVersion: infra.modeld.io/v1alpha1
kind: VirtualBucket
metadata:
  name: default-minio-bucket
  namespace: default-tenant
spec:
  tenantRef:
    namespace: modeld-system
    name : default-tenant
  credentialName: default-minio

{{- end }}