{{ if .Values.slack.create }}
apiVersion: infra.modeld.io/v1alpha1
kind: Credential
metadata:
  name: default-slack-credential
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
spec:
  provider: slack
  tenantRef:
    name: default-tenant
    namespace: {{ .Release.Namespace }}
  secretName : default-slack-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: default-slack-secret
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.slack.secret.username }}
  slack-username : {{ .Values.slack.secret.username | b64enc | quote }}
  {{ else }}
  slack-username : {{ required "slack username is required!" .Values.slack.secret.username }}
  {{- end }}
  {{- if .Values.slack.secret.token }}
  slack-token : {{ .Values.slack.secret.token | b64enc | quote }}
  {{ else }}
  slack-token : {{ required "slack token  is required!" .Values.slack.secret.token }}
  {{- end }}
{{ end }}
