apiVersion: v1
kind: Service
metadata:
  name: modeld-apigateway-service
  namespace: modeld-system
  labels: {{- include "modeld.apigateway.labels" . | nindent 4 }}
spec:
  ports:
    - name: apigateway
      port: {{ .Values.apigateway.http.port }}
      targetPort: apigateway
  selector: {{- include "modeld.apigateway.matchLabels" . | nindent 4 }}