apiVersion: v1
kind: Service
metadata:
  name: modeld-dataplane-service
  namespace: modeld-system
  labels: {{- include "modeld.dataplane.labels" . | nindent 4 }}
spec:
  ports:
    - name: dataplane
      port: {{ .Values.dataplane.http.port }}
      targetPort: dataplane
  selector: {{- include "modeld.dataplane.matchLabels" . | nindent 4 }}