apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modeld-publisher-role
  namespace: modeld-system
  labels: {{- include "modeld.publisher.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch