{{ if .Values.servingsite.create }}
apiVersion: infra.modeld.io/v1alpha1
kind: ServingSite
metadata:
  name: default-serving-site
  namespace: default-tenant
spec:
  fdqn: {{ .Values.servingsite.fdqn }}
  ingressref:
    namespace: default-tenant
    name: default-ingress
  tenantRef:
    name: default-tenant
    namespace: {{ .Release.Namespace }}
{{ end }}