apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: modeld-service-role-binding
  namespace: modeld-system
  labels:
    app: {{ template "modeld.name" . }}
    chart: {{ template "modeld.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-cluster-role
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccount:modeld-system:modeld-service-account
