name: Lint and Test Charts

on:
  watch:
    types: [started]

jobs:
   lint-chart:
      runs-on: ubuntu-latest
      steps:
              - name: Checkout
                uses: actions/checkout@v1
              - name: Run chart-testing (lint)
                uses: helm/chart-testing-action@master
                with:
                  command: lint
                  config: .github/ct.yaml
   lint-docs:
     runs-on: ubuntu-latest
     needs: lint-chart
     steps:
       - name: Checkout
         uses: actions/checkout@v1
       - name: Run helm-docs
         run: .github/helm-docs.sh

   publish:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - uses: J12934/helm-gh-pages-action@master
         with:
           access-token: ${{ secrets.ACCESS_TOKEN }}